"""add source article event_cluster tables

Revision ID: 6ecfe7e6ea44
Revises: d697b1d1d6be
Create Date: 2026-02-27 17:19:22.425091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ecfe7e6ea44'
down_revision: Union[str, Sequence[str], None] = 'd697b1d1d6be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_clusters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=512), nullable=False),
    sa.Column('debiased_summary', sa.Text(), nullable=True),
    sa.Column('ner_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='clusterstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_clusters_embedding_id'), 'event_clusters', ['embedding_id'], unique=False)
    op.create_index(op.f('ix_event_clusters_label'), 'event_clusters', ['label'], unique=False)
    op.create_index(op.f('ix_event_clusters_status'), 'event_clusters', ['status'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('feed_url', sa.String(length=2048), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_name'), 'sources', ['name'], unique=True)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=1024), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', name='uq_articles_url')
    )
    op.create_index(op.f('ix_articles_source_id'), 'articles', ['source_id'], unique=False)
    op.create_index(op.f('ix_articles_url'), 'articles', ['url'], unique=True)
    op.create_table('article_event_cluster',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('event_cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_cluster_id'], ['event_clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'event_cluster_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_event_cluster')
    op.drop_index(op.f('ix_articles_url'), table_name='articles')
    op.drop_index(op.f('ix_articles_source_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_sources_name'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_event_clusters_status'), table_name='event_clusters')
    op.drop_index(op.f('ix_event_clusters_label'), table_name='event_clusters')
    op.drop_index(op.f('ix_event_clusters_embedding_id'), table_name='event_clusters')
    op.drop_table('event_clusters')
    # ### end Alembic commands ###
