"""link_contradiction_positions_to_sources

Revision ID: 8d6d29986f21
Revises: eb8ac5583d85
Create Date: 2026-03-06 14:57:46.416905

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d6d29986f21'
down_revision: Union[str, None] = 'eb8ac5583d85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contradiction_positions', sa.Column('source_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_contradiction_positions_source_id', 'contradiction_positions', 'sources', ['source_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_contradiction_positions_source_id', 'contradiction_positions', type_='foreignkey')
    op.drop_column('contradiction_positions', 'source_id')
    # ### end Alembic commands ###
