"""add_sources_table

Revision ID: eb8ac5583d85
Revises: 0001_initial_schema
Create Date: 2026-03-06 14:38:56.651341

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb8ac5583d85'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Enum('RSS', 'FINANCIAL', 'SOCIAL', name='source_type'), nullable=False),
    sa.Column('spectrum_score', sa.Float(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('cluster_sources', sa.Column('source_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_cluster_sources_source_id', 'cluster_sources', 'sources', ['source_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_cluster_sources_source_id', 'cluster_sources', type_='foreignkey')
    op.drop_column('cluster_sources', 'source_id')
    op.drop_table('sources')
    # ### end Alembic commands ###
